
### @name login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "username": "user",
    "password": "password123"
}

###


GET http://localhost:3000/protected
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzIjoxNzQ1MTg5NjUzLCJpc3N1ZWRfYXQiOjE3NDUxODYwNTMsImp0aSI6ImFiZThlMjgxLTZlZmEtNGJlYS1hY2ZlLWQ0MDMzNDFjNWJiMyIsInVzZXJfaWQiOjEyMzEzMjEzLCJ1c2VybmFtZSI6InVzZXIifQ.VW7GQDy_1dJ92s39l6iSx1bwrYINPPm-t264uFFfybU

###
GET http://localhost:3000/hello

###