// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database_sql

import (
	"database/sql"
	"time"
)

type Token struct {
	Jti       string
	UserID    int64
	ExpiresAt time.Time
	IsRevoked sql.NullBool
}

type User struct {
	UserID       interface{}
	Username     sql.NullString
	PasswordHash sql.NullString
	S            interface{}
	LastLogin    time.Time
}
